name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: npm install -g npm@7
      working-directory: ./codebase/rdicidr-0.1.0/
    - run: npm ci
      working-directory: ./codebase/rdicidr-0.1.0/
    - run: npm run lint
      working-directory: ./codebase/rdicidr-0.1.0/
    - run: npm run prettier
      working-directory: ./codebase/rdicidr-0.1.0/
    - run: CI=true npm run test
      working-directory: ./codebase/rdicidr-0.1.0/
    - run: npm run build